### ISSUE TITLE
Different Folder

### ISSUE THREAD

**Issue by Erdmanny** [Xceron/Filecrawl#4]
Hey Xceron,
first of all, I'm loving your program, saves a lot of work!
I just have a suggestion! Could you make it possible to insert the files into user-defined folders and rename them?
Unfortunately I have no experience with Python and can't do it myself.

**Comment by Xceron** [comment]
Hey Erdmanny!

Thank you for your kind words!
Im working on a version which lets you rename files which are located in the "right" folder, so i hope this will solve your issue!

**Comment by Xceron** [comment]
Added enhancement with the latest [commit](https://github.com/Xceron/Filecrawl/commit/a9ec2c1eaab6cfde0f7a86d2c36f6ab712cf6966)
